/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package sdu.embedded;

public final class R {
    public static final class array {
        public static final int action=0x7f060000;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int whitee=0x7f020001;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f090001;
        public static final int LinearLayout02=0x7f090006;
        public static final int MyLinearLayout0=0x7f090003;
        public static final int MyLinearLayout1=0x7f090004;
        public static final int RelativeLayout01=0x7f090007;
        public static final int SurfaceView01=0x7f09000b;
        public static final int action_settings=0x7f09000c;
        public static final int btnExit=0x7f090005;
        public static final int btnStart=0x7f090002;
        public static final int iv_main_pic=0x7f090000;
        public static final int media=0x7f09000a;
        public static final int need=0x7f090009;
        public static final int phone=0x7f090008;
    }
    public static final class layout {
        public static final int fragment_picture_slide=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int main=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f070000;
        public static final int app_name=0x7f070001;
        public static final int btn_exit=0x7f070002;
        public static final int btn_start=0x7f070003;
        public static final int hello=0x7f070004;
    }
    public static final class style {
        /**  API 11 theme customizations can go here. 
 API 14 theme customizations can go here. 

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f040000;
        /**  All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f040001;
    }
}
