######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 10 15:15:27 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello_qt.cpp
