######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 9 14:55:35 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
